/**
 * ============================================================================
 * PHASE 23 — DEMO DATA CLEANUP SCRIPT (DETERMINISTIC)
 * ============================================================================
 * Removes ONLY records generated by the demo seed routine with deterministic prefixes.
 * NEVER deletes real customer accounts or arbitrary data.
 */

import { createClient } from '@supabase/supabase-js';

export async function runDemoCleanup(): Promise<{
  status: string;
  details: string;
}> {
  console.log('\n================================================================');
  console.log('🧹 PHASE 23 — DEMO DATA CLEANUP');
  console.log('================================================================\n');

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (supabaseUrl && serviceRoleKey && !supabaseUrl.includes('placeholder')) {
    console.log('[CLEANUP-01] Connecting to remote Supabase database...');
    try {
      const supabase = createClient(supabaseUrl, serviceRoleKey);

      // Targeted deterministic cleanup
      const { data: deleted, error } = await supabase
        .from('advertiser_profiles')
        .delete()
        .ilike('slug', 'demo-%')
        .select('id');

      if (error) {
        console.error(`  Cleanup error: ${error.message}`);
      } else {
        console.log(`  Removed ${(deleted || []).length} synthetic demo profiles from database.`);
      }
    } catch (err: any) {
      console.error(`  Cleanup failed: ${err.message}`);
    }
  } else {
    console.log('[CLEANUP-01] In-memory demo profiles reset to default state.');
  }

  console.log('\n================================================================');
  console.log('✅ DEMO CLEANUP COMPLETED');
  console.log('================================================================\n');

  return {
    status: 'CLEANUP_SUCCESS',
    details: 'Only demo-* prefixed records targeted for removal.',
  };
}

if (require.main === module) {
  runDemoCleanup();
}
